### ISSUE TITLE
Apollo client error 

### ISSUE THREAD

**Issue by pociej** [apollographql/meteor-starter-kit#42]
Client side , every time i see : 
```modules.js?hash=b22a364…:26013 Error in observer.error 
Error
    at new ApolloError (http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:26607:23)
    at http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:26004:39
    at http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:26492:25
    at Array.forEach (native)
    at http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:26489:27
    at http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:29106:11
    at baseForOwn (http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:29048:20)
    at forOwn (http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:34321:20)
    at QueryManager.broadcastQueries (http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:26487:9)
    at Array.<anonymous> (http://localhost:3000/packages/modules.js?hash=b22a36479231cbdd456c96d761588687dc57c31d:25920:23)```

**Comment by martinhbramwell** [comment]
@pociej 
Have you tried in a browser that offers better error reporting?
Have you altered anything?
Which branch are you using?
What operating system?

**Comment by comus** [comment]
the same. just git clone and meteor npm install and meteor run it.
client show the same errors.
and at the same time server shows
```
W20170103-00:30:22.797(8)? (STDERR) TypeError: Cannot read property 'userId' of undefined
W20170103-00:30:23.013(8)? (STDERR)     at user (imports/api/schema.js:29:11)
W20170103-00:30:23.014(8)? (STDERR)     at resolveOrError (/Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql/execution/execute.js:454:12)
W20170103-00:30:23.014(8)? (STDERR)     at resolveField (/Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql/execution/execute.js:445:16)
W20170103-00:30:23.015(8)? (STDERR)     at /Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql/execution/execute.js:252:18
W20170103-00:30:23.015(8)? (STDERR)     at Array.reduce (native)
W20170103-00:30:23.015(8)? (STDERR)     at executeFields (/Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql/execution/execute.js:249:42)
W20170103-00:30:23.016(8)? (STDERR)     at executeOperation (/Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql/execution/execute.js:190:10)
W20170103-00:30:23.016(8)? (STDERR)     at /Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql/execution/execute.js:116:13
W20170103-00:30:23.016(8)? (STDERR)     at Object.execute (/Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql/execution/execute.js:115:10)
W20170103-00:30:23.017(8)? (STDERR)     at doRunQuery (/Users/chris/Desktop/new/meteor-starter-kit/node_modules/graphql-server-core/dist/runQuery.js:77:26)
```

**Comment by comus** [comment]
may be modify  imports/api/schema.js:29
```
if (context.userId === args.id) {
```
change to
```
if (context && context.userId === args.id) {
```

**Comment by xavcz** [comment]
Got fixed: `createApolloServer` creates an empty `context` object by default, and eventually feed it with `user` and `userId` if one is logged in 👍
