### ISSUE TITLE
Get error after update to meteor 1.4.3.2

### ISSUE THREAD

**Issue by liu0fanyi** [apollographql/meteor-starter-kit#47]
update info:
```bash
Changes to your project's package version selections from updating the release:

accounts-base     upgraded from 1.2.14 to 1.2.15
ddp-rate-limiter  upgraded from 1.0.6 to 1.0.7
http              upgraded from 1.2.11 to 1.2.12
minimongo         upgraded from 1.0.20 to 1.0.21
mongo             upgraded from 1.1.15 to 1.1.16
npm-mongo         upgraded from 2.2.16_1 to 2.2.24
observe-sequence  upgraded from 1.0.15 to 1.0.16
rate-limit        upgraded from 1.0.6 to 1.0.7
webapp            upgraded from 1.3.13 to 1.3.14

meteor-starter-kit: updated to Meteor 1.4.3.2.

Changes to your project's package version selections from updating package versions:

apollo                 upgraded from 0.5.0 to 0.6.0
blaze                  upgraded from 2.3.0 to 2.3.1
caching-html-compiler  upgraded from 1.1.0 to 1.1.1
spacebars              upgraded from 1.0.13 to 1.0.14
spacebars-compiler     upgraded from 1.1.0 to 1.1.1
templating-tools       upgraded from 1.1.0 to 1.1.1
```

error info
```bash
W20170318-14:07:52.346(8)? (STDERR) /Users/mac/.meteor/packages/meteor-tool/.1.4.3_2.gnbf6n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170318-14:07:52.448(8)? (STDERR) 						throw(ex);
W20170318-14:07:52.449(8)? (STDERR) 						^
W20170318-14:07:52.449(8)? (STDERR)
W20170318-14:07:52.450(8)? (STDERR) Error: Can't find npm module 'subscriptions-transport-ws'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170318-14:07:52.450(8)? (STDERR)     at Object.require (/Users/mac/learn/apollo/meteor-starter-kit/.meteor/local/build/programs/server/boot.js:200:17)
W20170318-14:07:52.450(8)? (STDERR)     at options.fallback (packages/modules-runtime.js:479:18)
W20170318-14:07:52.451(8)? (STDERR)     at Module.require (packages/modules-runtime.js:126:16)
W20170318-14:07:52.452(8)? (STDERR)     at Module.Mp.import (/Users/mac/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-14:07:52.452(8)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-client.js (packages/apollo/src/main-client.js:1:434)
W20170318-14:07:52.452(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170318-14:07:52.453(8)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170318-14:07:52.453(8)? (STDERR)     at Module.Mp.import (/Users/mac/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-14:07:52.453(8)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-server.js (packages/apollo/src/main-server.js:1:75)
W20170318-14:07:52.453(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
W20170318-14:07:55.094(8)? (STDERR) /Users/mac/.meteor/packages/meteor-tool/.1.4.3_2.gnbf6n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170318-14:07:55.095(8)? (STDERR) 						throw(ex);
W20170318-14:07:55.095(8)? (STDERR) 						^
W20170318-14:07:55.096(8)? (STDERR)
W20170318-14:07:55.096(8)? (STDERR) Error: Can't find npm module 'subscriptions-transport-ws'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170318-14:07:55.096(8)? (STDERR)     at Object.require (/Users/mac/learn/apollo/meteor-starter-kit/.meteor/local/build/programs/server/boot.js:200:17)
W20170318-14:07:55.097(8)? (STDERR)     at options.fallback (packages/modules-runtime.js:479:18)
W20170318-14:07:55.097(8)? (STDERR)     at Module.require (packages/modules-runtime.js:126:16)
W20170318-14:07:55.097(8)? (STDERR)     at Module.Mp.import (/Users/mac/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-14:07:55.098(8)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-client.js (packages/apollo/src/main-client.js:1:434)
W20170318-14:07:55.099(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170318-14:07:55.099(8)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170318-14:07:55.100(8)? (STDERR)     at Module.Mp.import (/Users/mac/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-14:07:55.101(8)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-server.js (packages/apollo/src/main-server.js:1:75)
W20170318-14:07:55.101(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
W20170318-14:07:57.602(8)? (STDERR) /Users/mac/.meteor/packages/meteor-tool/.1.4.3_2.gnbf6n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170318-14:07:57.603(8)? (STDERR) 						throw(ex);
W20170318-14:07:57.603(8)? (STDERR) 						^
W20170318-14:07:57.604(8)? (STDERR)
W20170318-14:07:57.604(8)? (STDERR) Error: Can't find npm module 'subscriptions-transport-ws'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170318-14:07:57.605(8)? (STDERR)     at Object.require (/Users/mac/learn/apollo/meteor-starter-kit/.meteor/local/build/programs/server/boot.js:200:17)
W20170318-14:07:57.605(8)? (STDERR)     at options.fallback (packages/modules-runtime.js:479:18)
W20170318-14:07:57.605(8)? (STDERR)     at Module.require (packages/modules-runtime.js:126:16)
W20170318-14:07:57.606(8)? (STDERR)     at Module.Mp.import (/Users/mac/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-14:07:57.606(8)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-client.js (packages/apollo/src/main-client.js:1:434)
W20170318-14:07:57.607(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170318-14:07:57.608(8)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170318-14:07:57.608(8)? (STDERR)     at Module.Mp.import (/Users/mac/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-14:07:57.609(8)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-server.js (packages/apollo/src/main-server.js:1:75)
W20170318-14:07:57.609(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by xavcz** [comment]
Just updated the dependencies, the issue came from missing node deps (`subscriptions-transport-ws` & `graphql-subscriptions`)
